### ISSUE TITLE
Add support for tailing oplog

### ISSUE THREAD

**Issue by stennie** [mrsarm/mongotail#1]
It would be great to add support for [tailing the oplog](http://docs.mongodb.org/manual/tutorial/create-tailable-cursor/) as an alternative to using system profile data.

For a deployment with the oplog enabled (i.e. a replica set, although this can be enabled on a standalone node):
- there's no extra write overhead to view all insert/update/remove operations (as compared to system profiling level 2)
- write operations can be tracked across multiple databases with a single tail command

**Comment by mrsarm** [comment]
Yes, I thought that, but according with [oplog documentation](http://docs.mongodb.org/manual/core/replica-set-oplog/), only _"operations that modify the data stored in your databases"_ are recorded, so **find** or any **cursor operations** will not saved.

**Comment by stennie** [comment]
@mrsarm That's correct .. the oplog would only include operations that affect data so you'd still need system profiling for query data.

The format in the oplog also isn't identical to the original query/update, but could still be useful to track changes to data without enabling profiling.
