### ISSUE TITLE
Feature request: Option to display query time

### ISSUE THREAD

**Issue by r1b** [mrsarm/mongotail#10]
And/or other metadata

**Comment by mrsarm** [comment]
Do you want to see how much time a query takes? Yes, could be a good "optional" feature, and I liked the idea about add more metadata optionally, even the time, maybe with a parameter like `--metadata querytime` for example. Right?

**Comment by r1b** [comment]
Yes! I have a modified version of mongotail locally that pulls out `millis` and displays it for each query. If you think it would be valuable to do this in a more general way that would be awesome. It is pretty easy to pull out whatever metadata you want, displaying it in a general way is trickier.

**Comment by mrsarm** [comment]
@r1b I'm working on this, and also in add support to some changes in MongoDB 3.2 log format. But testing with Mongo 2.8, 3.0 and 3.2, I cannot see the property `millis` or any other property from the profile log that give me the time of the operation.

Could you give me more information about your environment and how you get this information? What version of MongoDB do you have?

**Comment by mrsarm** [comment]
@r1b Dismiss my comment, I did the test wrong. Now I see the `millis` property in the logs.

**Comment by mrsarm** [comment]
@r1b I added two options for this:
- `-m`, `--metadata` option to add extra metadata fields to show.
- `-v`, `--verbose` option to print all the operations in JSON without format.

I going to release the version 2.0.0 with these and others improvements. Please, take a look on this and give me a feedback if this doesn't work for you.

**Comment by r1b** [comment]
Looks great! Thanks so much. I will close this issue.
